# Generated by Django 4.2.7 on 2023-12-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='docname',
            field=models.CharField(default='DOC', max_length=220),
        ),
    ]
