# Generated by Django 4.2.7 on 2023-12-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_document_docname'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='first_name',
            field=models.CharField(default='JOHN', max_length=220),
        ),
        migrations.AddField(
            model_name='document',
            name='second_name',
            field=models.CharField(default='DOE', max_length=220),
        ),
    ]
