# Generated by Django 4.2.7 on 2024-01-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_document_first_name_document_second_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='document',
            name='docname',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='document',
            name='first_name',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='document',
            name='second_name',
            field=models.CharField(max_length=220),
        ),
    ]
