# Generated by Django 4.2.7 on 2024-01-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_document_email_alter_document_docname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='details',
            field=models.TextField(default=''),
        ),
    ]
