# Generated by Django 4.2.7 on 2024-01-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_alter_document_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='details',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
