# Generated by Django 4.2.7 on 2024-01-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_alter_document_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='details',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='docname',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
